/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.optics;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.zip.DataFormatException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Omar AbuRish
 */
public class ExamsPanel extends javax.swing.JFrame {

    /**
     * Creates new form ExamsPanel
     */
    Patient currentPatient; 
    int numberOfExams , currentExamIndex = 0;
    Examination currentExam ; 
    Logger log ;
    ArrayList<Patient> patients;
    private boolean addingNewExam = false;
    
    
    public ExamsPanel(Patient p , Logger log , ArrayList<Patient> patients) {
        
        initComponents();
        this.log = log;
        this.patients = patients;
        currentPatient = p ; 
        updateExamFields();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setPatientFields();
    }
    
    
    public void setPatientFields() {
        idTextField.setText(currentPatient.getId()+ "");
        patientNameTextField.setText(currentPatient.getName());
        patientBirthDateTextField.setText(currentPatient.getBirthDate().getYear() + "");
    }
    public void updateExamFields() {
        numberOfExams  = currentPatient.getNumberOfExams();
        Examination currentExam = currentPatient.getExams().get(currentExamIndex);
        
        nextAndPreviousButtonEnabler();
        
        
        examDateTextField.setText(currentExam.getExamDate().format(DateTimeFormatter.ISO_LOCAL_DATE).toString());
        examHourTextField.setText(currentExam.getExamDate().format(DateTimeFormatter.ofPattern("HH:mm")).toString());
        rightCylinderTextField.setText(currentExam.getRightCylinder() + "");
        rightAxisTextField.setText(currentExam.getRightAxis() + "");
        rightSphereTextField.setText(currentExam.getRightSphere() + "");
        
        leftCylinderTextField.setText(currentExam.getLeftCylinder() + "");
        leftAxisTextField.setText(currentExam.getLeftAxis() + "");
        leftSphereTextField.setText(currentExam.getLeftSphere() + "");
        
        nearTextField.setText(currentExam.getNear() + "");
        noteTextField.setText(currentExam.getNote());
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        patientNameTextField = new javax.swing.JTextField();
        patientBirthDateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        leftCylinderTextField = new javax.swing.JTextField();
        leftAxisTextField = new javax.swing.JTextField();
        leftSphereTextField = new javax.swing.JTextField();
        rightAxisTextField = new javax.swing.JTextField();
        rightCylinderTextField = new javax.swing.JTextField();
        rightSphereTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        examDateTextField = new javax.swing.JTextField();
        nearTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        noteTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        examHourTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        changeEnableButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addNewExamButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientNameTextField.setEnabled(false);

        patientBirthDateTextField.setEnabled(false);
        patientBirthDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBirthDateTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("سنة الميلاد");

        jLabel2.setText("الاسم");

        leftCylinderTextField.setEnabled(false);
        leftCylinderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftCylinderTextFieldActionPerformed(evt);
            }
        });

        leftAxisTextField.setEnabled(false);
        leftAxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftAxisTextFieldActionPerformed(evt);
            }
        });

        leftSphereTextField.setEnabled(false);
        leftSphereTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftSphereTextFieldActionPerformed(evt);
            }
        });

        rightAxisTextField.setEnabled(false);
        rightAxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightAxisTextFieldActionPerformed(evt);
            }
        });

        rightCylinderTextField.setEnabled(false);
        rightCylinderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightCylinderTextFieldActionPerformed(evt);
            }
        });

        rightSphereTextField.setEnabled(false);
        rightSphereTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightSphereTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Right");

        jLabel7.setText("Left");

        jLabel8.setText("Sphere");

        jLabel9.setText("Axis");

        jLabel10.setText("Cylinder");

        jLabel11.setText("Axis");

        jLabel12.setText("Sphere");

        jLabel13.setText("Cylinder");

        jLabel5.setText("تاريخ الفحص");

        examDateTextField.setEnabled(false);
        examDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examDateTextFieldActionPerformed(evt);
            }
        });

        nearTextField.setEnabled(false);
        nearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Near");

        noteTextField.setEnabled(false);
        noteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Note");

        jLabel16.setText("ساعة الفحص");

        examHourTextField.setEnabled(false);
        examHourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examHourTextFieldActionPerformed(evt);
            }
        });

        nextButton.setText("التالي");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("السابق");
        previousButton.setEnabled(false);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        saveButton.setText("حفظ");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        changeEnableButton.setText("اضغط هنا للتعديل");
        changeEnableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(rightSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightAxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(examDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(examHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(leftSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftAxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(nearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(88, 88, 88))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addGap(43, 43, 43)
                        .addComponent(changeEnableButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(saveButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousButton)
                .addGap(127, 127, 127))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightAxisTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rightSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(rightCylinderTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftAxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(previousButton)
                    .addComponent(changeEnableButton))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap())
        );

        idTextField.setEditable(false);
        idTextField.setEnabled(false);

        jLabel4.setText("الرقم التعريفي");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientBirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameTextField)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientBirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        addNewExamButton.setText("إضافة فحص جديد");
        addNewExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewExamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(addNewExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewExamButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientBirthDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBirthDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBirthDateTextFieldActionPerformed

    private void leftCylinderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftCylinderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftCylinderTextFieldActionPerformed

    private void leftAxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftAxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftAxisTextFieldActionPerformed

    private void leftSphereTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftSphereTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftSphereTextFieldActionPerformed

    private void rightAxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightAxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightAxisTextFieldActionPerformed

    private void rightCylinderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightCylinderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightCylinderTextFieldActionPerformed

    private void rightSphereTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightSphereTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightSphereTextFieldActionPerformed

    private void examDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examDateTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_examDateTextFieldActionPerformed

    private void nearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nearTextFieldActionPerformed

    private void noteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTextFieldActionPerformed

    private void examHourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examHourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examHourTextFieldActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        currentExamIndex++;
        
        updateExamFields();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        currentExamIndex--;
        updateExamFields();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void updatePatientData() throws NumberFormatException{
        currentPatient.setId(Integer.parseInt(idTextField.getText() ));
        currentPatient.setName(patientNameTextField.getText());
        patientBirthDateTextField.getText();
        currentPatient.setBirthDate(new Date(1, 1, Integer.parseInt(patientBirthDateTextField.getText())));
        
    }
    
    
    private LocalDateTime checkTimeValidity() throws DateTimeParseException {
        try {
            String str = examDateTextField.getText() + " " + examHourTextField.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"); 
            LocalDateTime dateTime = LocalDateTime.parse(str, formatter);
            return dateTime;
        } catch(DateTimeParseException e) {
            throw e ;
        }
    }
    private void checkDataValidity() throws NumberFormatException{
        try {
            currentExam = currentPatient.getExams().get(currentExamIndex);
            Integer.parseInt(idTextField.getText());
            Integer.parseInt(patientBirthDateTextField.getText());
            
            Float.parseFloat(rightSphereTextField.getText());
            Float.parseFloat(rightCylinderTextField.getText());
            Float.parseFloat(rightAxisTextField.getText());
            Float.parseFloat(leftSphereTextField.getText());
            Float.parseFloat(leftCylinderTextField.getText());
            Float.parseFloat(leftAxisTextField.getText());
            Float.parseFloat(nearTextField.getText());
        }
        catch (NumberFormatException e) {
            throw e;
        }
        
    }
    
    private void updateExamData() throws DateTimeParseException{
        try {
            LocalDateTime examDate = checkTimeValidity();
            currentExam.setExamDate(examDate);

            currentExam.setLeftAxis(Float.parseFloat(leftAxisTextField.getText()));
            currentExam.setLeftCylinder(Float.parseFloat(leftCylinderTextField.getText()));
            currentExam.setLeftSphere(Float.parseFloat(leftSphereTextField.getText()));
            currentExam.setRightAxis(Float.parseFloat(rightAxisTextField.getText()));
            currentExam.setRightCylinder(Float.parseFloat(rightCylinderTextField.getText()));
            currentExam.setRightSphere(Float.parseFloat(rightSphereTextField.getText()));
            currentExam.setNear(Float.parseFloat(nearTextField.getText()));
            currentExam.setNote(noteTextField.getText());
        } catch (DateTimeParseException e ){
            throw e; 
        }
        
    }
    
    private void nextAndPreviousButtonEnabler() {
        if(currentExamIndex < numberOfExams - 1 ) {
            nextButton.setEnabled(true);
        }
        else {
            nextButton.setEnabled(false);
        }
        
        if(currentExamIndex > 0 ) {
            previousButton.setEnabled(true);
        }
        else {
            previousButton.setEnabled(false);
        }
    }
    
    private void addNewExam() {
        try { 
            
            Patient examedPatient = currentPatient;


             String str = examDateTextField.getText() + " " + examHourTextField.getText();
             DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"); 
             LocalDateTime dateTime = LocalDateTime.parse(str, formatter);

             examedPatient.addExam(new Examination(
                     dateTime, 
                     Float.parseFloat(rightSphereTextField.getText()),
                     Float.parseFloat(rightCylinderTextField.getText()),
                     Float.parseFloat(rightAxisTextField.getText()),
                     Float.parseFloat(leftSphereTextField.getText()),
                     Float.parseFloat(leftCylinderTextField.getText()),
                     Float.parseFloat(leftAxisTextField.getText()),
                     Float.parseFloat(nearTextField.getText()),
                     noteTextField.getText()
             ));


             
             toggleButtons(false);
             log.writeToFile(patients);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "البيانات ليست صحيحة يرجى وضعها مرة أخرى");
        }  
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            checkDataValidity();
            
            if(addingNewExam == true) {
                examDateTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE));
                examHourTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
                addNewExam();
                toggleButtons(false);
                
                JOptionPane.showMessageDialog(rootPane, "تم إضافة الفحص بنجاح");
                addingNewExam = false ; 
                
                resetFields();
                currentExamIndex = currentPatient.getExams().size() - 1;
                updateExamFields();
                toggleSaveButton();
            } else {
                updatePatientData();
                updateExamData();

                changeEnableButton.setEnabled(true);
                toggleButtons(false);
                nextAndPreviousButtonEnabler();
                JOptionPane.showMessageDialog(rootPane, "تم تعديل البيانات بنجاح");
            }
            
            
            log.writeToFile(patients);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "المعلومات المدخلة غير صحيحة يرجى تعديلها");
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(rootPane, "المعلومات المدخلة غير صحيحة يرجى تعديلها");
        }
        
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void toggleButtons(boolean state) {
        saveButton.setEnabled(state);
        
        patientNameTextField.setEnabled(state);
        patientBirthDateTextField.setEnabled(state);
        
        examDateTextField.setEnabled(state);
        examHourTextField.setEnabled(state);
        rightAxisTextField.setEnabled(state);
        rightCylinderTextField.setEnabled(state);
        rightSphereTextField.setEnabled(state);
        
        leftAxisTextField.setEnabled(state);
        leftCylinderTextField.setEnabled(state);
        leftSphereTextField.setEnabled(state);
        
        noteTextField.setEnabled(state);
        nearTextField.setEnabled(state);
        
        
        nextButton.setEnabled(!state);
        previousButton.setEnabled(!state);
        changeEnableButton.setEnabled(!state);
    }
    private void changeEnableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnableButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(true);
        
        patientNameTextField.setEnabled(true);
        patientBirthDateTextField.setEnabled(true);
        
        examDateTextField.setEnabled(true);
        examHourTextField.setEnabled(true);
        rightAxisTextField.setEnabled(true);
        rightCylinderTextField.setEnabled(true);
        rightSphereTextField.setEnabled(true);
        
        leftAxisTextField.setEnabled(true);
        leftCylinderTextField.setEnabled(true);
        leftSphereTextField.setEnabled(true);
        
        noteTextField.setEnabled(true);
        nearTextField.setEnabled(true);
        
        
        nextButton.setEnabled(false);
        previousButton.setEnabled(false);
        changeEnableButton.setEnabled(false);
        
    }//GEN-LAST:event_changeEnableButtonActionPerformed

    
    private void resetFields() {
        idTextField.setText(currentPatient.getId() + "");
        patientNameTextField.setText(currentPatient.getName());
        patientBirthDateTextField.setText(currentPatient.getBirthDate().getYear() + "");
        examDateTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE));
        examHourTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        rightAxisTextField.setText("");
        rightCylinderTextField.setText("");
        rightSphereTextField.setText("");
        
        leftAxisTextField.setText("");
        leftCylinderTextField.setText("");
        leftSphereTextField.setText("");
        
        nearTextField.setText("");
        noteTextField.setText("");
    }
    
    private void toggleSaveButton() {
        String[] states = {"حفظ" , "إضافة فحص" };
        int stateIndex = 1;
        boolean state = false ; 
        if(addingNewExam == false) {
            state = true ; 
            stateIndex = 0 ; 
        }
        
        saveButton.setText(states[stateIndex]);
        nextButton.setVisible(state);
        previousButton.setVisible(state);
        changeEnableButton.setVisible(state);
    }
    private void addNewExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewExamButtonActionPerformed
        // TODO add your handling code here:
        resetFields();
        addingNewExam = true ;
        toggleSaveButton();
        saveButton.setText("إضافة الفحص");
        nextButton.setVisible(false);
        previousButton.setVisible(false);
        changeEnableButton.setVisible(false);
        
        
        saveButton.setEnabled(true);
        
        patientNameTextField.setEnabled(false);
        patientBirthDateTextField.setEnabled(false);
        
        examDateTextField.setEnabled(true);
        examHourTextField.setEnabled(true);
        rightAxisTextField.setEnabled(true);
        rightCylinderTextField.setEnabled(true);
        rightSphereTextField.setEnabled(true);
        
        leftAxisTextField.setEnabled(true);
        leftCylinderTextField.setEnabled(true);
        leftSphereTextField.setEnabled(true);
        
        noteTextField.setEnabled(true);
        nearTextField.setEnabled(true);
        
        addNewExamButton.setVisible(false);
        
    }//GEN-LAST:event_addNewExamButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewExamButton;
    private javax.swing.JButton changeEnableButton;
    private javax.swing.JTextField examDateTextField;
    private javax.swing.JTextField examHourTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField leftAxisTextField;
    private javax.swing.JTextField leftCylinderTextField;
    private javax.swing.JTextField leftSphereTextField;
    private javax.swing.JTextField nearTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JTextField patientBirthDateTextField;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField rightAxisTextField;
    private javax.swing.JTextField rightCylinderTextField;
    private javax.swing.JTextField rightSphereTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
