package javaapplication1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Dimension;
import java.awt.Image;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;


import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.imageio.ImageIO;

import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Omar AbuRish 
 */
public class OpticsApp extends javax.swing.JFrame {

    /**
     * Creates new form OpticsApp
     */
    
    ArrayList<Patient> patients = new ArrayList<>();
    ArrayList<Patient> wantedPatients = new ArrayList<>();
    
    Logger log ;
    
    int currentId = 0; 
    
    public OpticsApp() {
        
        initComponents();
        examDateTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE));
        examHourTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        
        
        /*BufferedImage img = null;
        try {
            java.net.URL imageURL = Optics.class.getResource("resourses/RazanIcon.jpeg");
            //new File("src/javaapplication1/resourses/RazanIcon.jpeg")
            img = ImageIO.read(imageURL);
            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
            Image.SCALE_SMOOTH);

            ImageIcon imageIcon = new ImageIcon(dimg);


            imageLabel.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }*/
        
        
        
        patientsNamesList.addMouseListener(new MouseAdapter(){
          @Override
            public void mouseClicked(MouseEvent evt) {
              
            if (evt.getClickCount() >= 2 ) {

                // Double-click detected
                int wantedIndex = patientsNamesList.getSelectedIndex();
                new ExamsPanel(wantedPatients.get(wantedIndex) , log , patients).setVisible(true);
            } 
           }
        });
        
        log = new Logger("log.dat");
        this.setTitle("Optics App");
        
        if(log.readPatients() != null) {
            
            patients = log.readPatients();
            
        }
            
        Integer.parseInt("+5");
        updatePatientsListByName("");
        
        currentId = patients.size() + 1 ;
        
        idTextField.setText(currentId + "");
        
        
        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)patientsNamesList.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.RIGHT);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        searchedNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsNamesList = new javax.swing.JList<>();
        searchedIdTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        patientNameTextField = new javax.swing.JTextField();
        patientBirthDateTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        leftCylinderTextField = new javax.swing.JTextField();
        leftAxisTextField = new javax.swing.JTextField();
        leftSphereTextField = new javax.swing.JTextField();
        rightAxisTextField = new javax.swing.JTextField();
        rightCylinderTextField = new javax.swing.JTextField();
        rightSphereTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        examDateTextField = new javax.swing.JTextField();
        nearTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        noteTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        examHourTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addExamButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchedNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchedNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchedNameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("البحث عن طريق الاسم");

        patientsNamesList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientsNamesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(patientsNamesList);

        searchedIdTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchedIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchedIdTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("البحث عن طريق الرقم التسلسلي");

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchButton.setText("بحث");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(searchedIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(searchedNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel17))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel1)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchedNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchedIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(searchButton))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("عرض الزبائن", jPanel5);

        patientNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        patientBirthDateTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientBirthDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBirthDateTextFieldActionPerformed(evt);
            }
        });

        leftCylinderTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leftCylinderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftCylinderTextFieldActionPerformed(evt);
            }
        });

        leftAxisTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leftAxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftAxisTextFieldActionPerformed(evt);
            }
        });

        leftSphereTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leftSphereTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftSphereTextFieldActionPerformed(evt);
            }
        });

        rightAxisTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightAxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightAxisTextFieldActionPerformed(evt);
            }
        });

        rightCylinderTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightCylinderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightCylinderTextFieldActionPerformed(evt);
            }
        });

        rightSphereTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightSphereTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightSphereTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Right");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Left");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Axis");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Sphere");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Cylinder");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("تاريخ الفحص");

        examDateTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        examDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examDateTextFieldActionPerformed(evt);
            }
        });

        nearTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Near");

        noteTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Note");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("ساعة الفحص");

        examHourTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        examHourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examHourTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(29, 29, 29)
                                                        .addComponent(examHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(examDateTextField))
                                                .addGap(66, 66, 66)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel13)
                                                .addGap(61, 61, 61)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(130, 130, 130))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rightCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(leftCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(rightAxisTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(leftAxisTextField))
                                        .addGap(102, 102, 102))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rightSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(leftSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(358, 358, 358))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(examDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(examHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(rightAxisTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rightSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rightCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftSphereTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftCylinderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftAxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("سنة الميلاد");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("الاسم");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("الرقم التعريفي");

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idTextField.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientBirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(idTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(patientNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(patientBirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addExamButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addExamButton.setText("إضافة الفحص");
        addExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(addExamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addExamButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("إضافة فحص لزبون جديد", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rightSphereTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightSphereTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightSphereTextFieldActionPerformed

    private void rightCylinderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightCylinderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightCylinderTextFieldActionPerformed

    private void rightAxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightAxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightAxisTextFieldActionPerformed

    private void leftSphereTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftSphereTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftSphereTextFieldActionPerformed

    private void leftAxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftAxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftAxisTextFieldActionPerformed

    private void leftCylinderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftCylinderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftCylinderTextFieldActionPerformed

    private void examDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examDateTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_examDateTextFieldActionPerformed

    private void patientBirthDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBirthDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBirthDateTextFieldActionPerformed

    private void nearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nearTextFieldActionPerformed

    private void noteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTextFieldActionPerformed

    private void searchedNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchedNameTextFieldActionPerformed
        // TODO add your handling code here:
        
        updatePatientsListByName(searchedNameTextField.getText());
    }//GEN-LAST:event_searchedNameTextFieldActionPerformed

    
    private void clearFields() {
        idTextField.setText(currentId + "");
        patientNameTextField.setText("");
        patientBirthDateTextField.setText("");
        examDateTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE));
        examHourTextField.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
        rightAxisTextField.setText("");
        rightCylinderTextField.setText("");
        rightSphereTextField.setText("");
        
        leftAxisTextField.setText("");
        leftCylinderTextField.setText("");
        leftSphereTextField.setText("");
        
        nearTextField.setText("");
        noteTextField.setText("");
        
        rightSphereTextField.setMinimumSize(new Dimension(64, 31));
    }
    
    
    
    private void addExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExamButtonActionPerformed
        // TODO add your handling code here:
        try { 
            int id = Integer.parseInt(idTextField.getText());
            String name = patientNameTextField.getText();
            int yearOfBirth = !patientBirthDateTextField.getText().isBlank()? Integer.parseInt(patientBirthDateTextField.getText()) : 0;
            if(!name.isBlank() && yearOfBirth != 0){
                Patient examedPatient = null ;
                boolean doesPatientExists = false;

                for (Patient p : patients) {
                     if(p.getName().equals(name)) {
                         // found person
                         System.out.println("is there");
                         doesPatientExists = true;
                         examedPatient = p ;
                         break;
                         
                     }
                 }
                

                 if(examedPatient == null){ 
                     System.out.println("Added new Patient");
                     patients.add(new Patient(name ,yearOfBirth , currentId));
                     currentId++;
                     
                     examedPatient = patients.get(patients.size() - 1) ;                                
                 }
                 
                 String str = examDateTextField.getText() + " " + examHourTextField.getText();
                 DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"); 
                 LocalDateTime dateTime = LocalDateTime.parse(str, formatter);
                 
                 
                 String nearText = nearTextField.getText();
                 float near = 0 ;
                 if(!nearText.isBlank()) {
                     near = Float.parseFloat(nearText);
                 }
                 examedPatient.addExam(new Examination(
                         dateTime, 
                         Float.parseFloat(rightSphereTextField.getText()),
                         Float.parseFloat(rightCylinderTextField.getText()),
                         Float.parseFloat(rightAxisTextField.getText()),
                         Float.parseFloat(leftSphereTextField.getText()),
                         Float.parseFloat(leftCylinderTextField.getText()),
                         Float.parseFloat(leftAxisTextField.getText()),
                         near,
                         noteTextField.getText()
                 ));
                 updatePatientsListByName("");
                 
                 clearFields();
                 JOptionPane.showMessageDialog(rootPane, "لقد تم إضافة الفحص");
                 log.writeToFile(patients);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "البيانات ليست كاملة يرجى إكمالها");
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "البيانات ليست صحيحة يرجى وضعها مرة أخرى");
        } 
        
        
        
    }//GEN-LAST:event_addExamButtonActionPerformed

    private void examHourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examHourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examHourTextFieldActionPerformed

    private void searchedIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchedIdTextFieldActionPerformed
        // TODO add your handling code here:
        updatePatientsListById();
    }//GEN-LAST:event_searchedIdTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(!searchedNameTextField.getText().isBlank()) {
            updatePatientsListByName(searchedNameTextField.getText());
            return ;
        }
        if (!searchedIdTextField.getText().isBlank()) {
            updatePatientsListById();
            return ;
        }
        updatePatientsListByName("");
    }//GEN-LAST:event_searchButtonActionPerformed

    
    public void updatePatientsListByName(String searchedName ) {
        
        wantedPatients.clear();
        System.out.println(searchedName);
        if(searchedName.isBlank()) {
            System.out.println("Blank");
            
            for(Patient i : patients) {
                 wantedPatients.add(i);
            }
        }
        else {
            wantedPatients = new ArrayList<>();
            for(Patient i : patients) {
                
                if(i.getName().contains(searchedName)) {
                    
                    wantedPatients.add(i);
                }
            }
            
        }
        String[] patientsNames = new String[wantedPatients.size()];
        
        for(int i = 0; i < wantedPatients.size() ; i++) {
            patientsNames[i] = wantedPatients.get(i).getId() +  "           " + wantedPatients.get(i).getName();
        }
        
        
        patientsNamesList.setListData(patientsNames);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new OpticsApp().setVisible(true);
            }
        });
    }
    
    public void updatePatientsListById() {
        
        try {
            wantedPatients.clear();
        
            if(searchedIdTextField.getText().isBlank()) {
                System.out.println("Blank");

                for(Patient i : patients) {
                     wantedPatients.add(i);
                }
            }
            else {
                int serachedId = Integer.parseInt(searchedIdTextField.getText());
                wantedPatients = new ArrayList<>();

                for(Patient i : patients) {

                    if(i.getId() == serachedId) {

                        wantedPatients.add(i);
                        break;
                    }
                }

            }
            String[] patientsNames = new String[wantedPatients.size()];
            
            for(int i = 0; i < wantedPatients.size() ; i++) {
                patientsNames[i] = wantedPatients.get(i).getId() +  "           " + wantedPatients.get(i).getName();
            }


            patientsNamesList.setListData(patientsNames);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "يرجى وضع رقم صحيح للبحث");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExamButton;
    private javax.swing.JTextField examDateTextField;
    private javax.swing.JTextField examHourTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField leftAxisTextField;
    private javax.swing.JTextField leftCylinderTextField;
    private javax.swing.JTextField leftSphereTextField;
    private javax.swing.JTextField nearTextField;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JTextField patientBirthDateTextField;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JList<String> patientsNamesList;
    private javax.swing.JTextField rightAxisTextField;
    private javax.swing.JTextField rightCylinderTextField;
    private javax.swing.JTextField rightSphereTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchedIdTextField;
    private javax.swing.JTextField searchedNameTextField;
    // End of variables declaration//GEN-END:variables
}
